### PR TITLE
DE36512 - fixed incorrect translation text

### PR DESCRIPTION
**Pull request by jeff-shepstone**
Text was Spanish and not French

### CODE REVIEW

**Comment by sarahboyd** [comment]
Thanks for updating these Jeff!! 

Looks like sauce/travis aren't too happy right now :( 
`Missing Sauce credentials. Did you forget to set SAUCE_USERNAME and/or SAUCE_ACCESS_KEY?`

**Comment by ChrisKraljevicD2L** [comment]
That would be because this PR is from a fork unfortunately.

**Comment by jeff-shepstone** [comment]
Thanks for sorting this out :) I just made an edit in the web interface of Github -- is there a better way to do this in the future?

Also, do you know if there's a specific way that I need to close the defect? It's currently assigned to my team, maybe it needs to be closed and moved over to your team for tracking purposes?

**Comment by sarahboyd** [comment]
> Thanks for sorting this out :) I just made an edit in the web interface of Github -- is there a better way to do this in the future?
> 
> Also, do you know if there's a specific way that I need to close the defect? It's currently assigned to my team, maybe it needs to be closed and moved over to your team for tracking purposes?

I think you would need write access to create a branch instead of a fork (which is why the build was failing). This works fine for small updates though :) 

And I've sent you an email about the rally defect.

**Pull request closed without merging**
