### PR TITLE
backport docreader changes

### PR DESCRIPTION
**Pull request by imcdonald-d2l**
Back porting @ianlaidlaw 's changes to docreader. Got weird behavior in the sidebar (nothing showed up) on local environment when back porting but I'm guessing it's because of some weird setup with BSI unbundled and updated components not inline with 20.20.6. Regardless this should be tested so we don't break the sidebar. The code changes below don't touch the sidebar so shouldn't be an issue 🤞

### CODE REVIEW

**Comment by sarahboyd** [comment]
Just wanna check on possibly adding a translation to this and then it's good to go 👍

**Comment by imcdonald-d2l** [comment]
> Just wanna check on possibly adding a translation to this and then it's good to go 👍

Just added the french translations @sarahboyd!

**Comment by sarahboyd** [comment]
> > Just wanna check on possibly adding a translation to this and then it's good to go 👍
> 
> Just added the french translations @sarahboyd!

Thank you!! Did you rerun `build:lang`? Need to update locales.json and localize-behaviour.js too

**Comment by imcdonald-d2l** [comment]
> > > Just wanna check on possibly adding a translation to this and then it's good to go 👍
> > 
> > 
> > Just added the french translations @sarahboyd!
> 
> Thank you!! Did you rerun `build:lang`? Need to update locales.json and localize-behaviour.js too

Ah good catch, I have not done that. Will do that now.

**Pull request merged**
